import type { GeneratedSections, Project } from "@/lib/types";

// Local demonstration only. This adapter deliberately makes no network calls.
export async function generateProjectSections(project: Project): Promise<{sections: GeneratedSections; mode: "mock"}> {
  const draft = "LOCAL TEMPLATE DRAFT - synthetic scenario; human review required.\n";
  return { mode: "mock", sections: {
    spec: `${draft}Project: ${project.name}\nProblem: ${project.businessProblem}\nUsers: ${project.businessTargetUsers}\nGoal: ${project.businessGoal}\nWorkflow: ${project.functionalWorkflows}\nRequirements: ${project.functionalRequirements}\nUnverified assumption: a guided intake plus human review fits this workflow.`,
    codeApproach: `${draft}Candidate components: intake UI, application API, project store, review screen.\nSystems to investigate: ${project.functionalSystems || "Not provided"}\nIntegrations to validate: ${project.functionalIntegrations || "Not provided"}\nNo integration or implementation is generated by this demo.`,
    securityGuardrails: `${draft}Data sources: ${project.functionalDataSources || "Not provided"}\nConstraints: ${project.businessConstraints || "Not provided"}\nNo authentication exists in this demo. Keep it on loopback. Before real use, define identity, ownership checks, retention, access logs and provider data rules.`,
    testStrategy: `${draft}Validate create, input save, template generation, edit and reload.\nAcceptance requirements to review: ${project.functionalRequirements}\nRisks to test: ${project.functionalRisks || "Not provided"}\nNo acceptance result for the proposed solution is asserted.`,
    productionPlan: `${draft}Not production-ready. Auth, billing, isolation, backup, rate limits and operational monitoring are absent.\nNon-functional targets to validate: ${project.nonFunctionalRequirements || "Not provided"}\nTimeline input, not an estimate: ${project.businessTimeline || "Not provided"}`,
    measurePlan: `${draft}Proposed metrics from input: ${project.businessKpis || "Not provided"}\nExpected outcome, not a measured result: ${project.businessOutcome || "Not provided"}\nCollect a baseline and agreed evaluation set before claiming improvement.`,
    improveRoadmap: `${draft}Review gaps, validate assumptions, then prioritize integrations and access control.\nKnown pain points: ${project.businessPainPoints || "Not provided"}\nBudget input, not a quote: ${project.businessBudget || "Not provided"}`,
    maturityModel: `${draft}Crawl: synthetic single-user evaluation.\nWalk: controlled pilot after identity and privacy work.\nRun: tested multi-user operations.\nFly: governance and measured quality.\nThese are planning stages, not current product capabilities.`,
    agileMapping: `${draft}Candidate epic: ${project.businessGoal}\nCandidate story: As ${project.businessTargetUsers}, I can complete ${project.functionalWorkflows}.\nSuggested slices: capture context, review a draft, collect feedback.\nAssumptions to validate: ${project.functionalAssumptions || "Not provided"}`
  }};
}
